# Generated by Django 3.1.12 on 2024-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20241130_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='last_alerted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
