# Generated by Django 5.1.3 on 2024-12-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_hospital_alter_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('symptoms', models.TextField()),
                ('criticalness', models.CharField(choices=[('critical', 'Critical'), ('non-critical', 'Non-Critical')], max_length=20)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('queue_status', models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted')], default='waiting', max_length=20)),
            ],
        ),
    ]
